apiVersion: v1
kind: Pod
metadata:
  name: health
  namespace: demo
spec:
  containers:
    - name: health
      image: mhausenblas/simpleservice:0.5.0
      ports:
        - containerPort: 9876
      livenessProbe: #! Probe para verificar si el contenedor esta vivo - MATA EL CONTENEDOR SI NO RESPONDE
        # readinessProbe: #! Probe para verificar si el contenedor esta listo - DETIENE EL TRAFFIC SI NO RESPONDE
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5 # Cuanto tiempo se espera para que la peticion sea exitosa
        failureThreshold: 3
        successThreshold: 1
        httpGet:
          path: /health
          port: 9876
      resources:
        requests: #Cantidad de recursos que se le asignan al contenedor
          cpu: 100m # 100 millicores
          memory: "100M" # 128 megabytes
        limits:
          cpu: 200m # 200 millicores
          memory: "200M" # 256 megabytes
